#!/usr/bin/env python3
"""
Genera el catálogo completo desde los datos extraídos del PDF.
No requiere librerías externas.
"""

import json
import re
from pathlib import Path

OUTPUT_DIR = Path("catalogo")

# Todos los productos extraídos del PDF (descripcion completa, precio)
PRODUCTOS_RAW = [
    # ── AFEER ────────────────────────────────────────────────────────────────
    ("BODY CREAM AFEER AL NOBLE WAZEER 250G",          14.50),
    ("BODY CREAM AFEER ANGEL 250G",                    14.50),
    ("BODY CREAM AFEER ASAD 250G",                     14.50),
    ("BODY CREAM AFEER DELILAH 250G",                  14.50),
    ("BODY CREAM AFEER FAKHAR MAN 250G",               14.50),
    ("BODY CREAM AFEER FAKHAR WOMEN 250G",             14.50),
    ("BODY CREAM AFEER MUSAMAM WHITE INTENSE 250G",    14.50),
    ("BODY CREAM AFEER NUIT ROYALE INTENSE MAN 250G",  14.50),
    ("BODY CREAM AFEER NUIT ROYALE WOMAN 250G",        14.50),
    ("BODY CREAM AFEER ROYAL AMBER 250G",              14.50),
    ("BODY CREAM AFEER SABAH AL WARD 250G",            14.50),
    ("BODY CREAM AFEER YARA 250G",                     14.50),
    ("BODY SPLASH AFEER ANGEL 200ML",                   9.50),
    ("BODY SPLASH AFEER DELILAH 200ML",                 9.50),
    ("BODY SPLASH AFEER FAKHAR WOMEN 200ML",            9.50),
    ("BODY SPLASH AFEER MUSAMAM WHITE INTENSE 200ML",   9.50),
    ("BODY SPLASH AFEER NUIT ROYALE WOMAN 200ML",       9.50),
    ("BODY SPLASH AFEER ROYAL AMBER 200ML",             9.50),
    ("BODY SPLASH AFEER SABAH AL WARD 200ML",           9.50),
    ("BODY SPLASH AFEER YARA 200ML",                    9.50),
    # ── AFNAN ────────────────────────────────────────────────────────────────
    ("PERFUME AFNAN 9PM EDP 100ML",                    19.45),
    ("PERFUME AFNAN 9PM ELIXIR PARFUM INTENSE 100ML",  27.95),
    # ── AL HARAMAIN ──────────────────────────────────────────────────────────
    ("PERFUME AL HARAMAIN AMBER OUD DUBAI NIGHT EDP 100ML",                  32.70),
    ("PERFUME AL HARAMAIN AMBER OUD GOLD 999.9 DUBAI EDITION EDP 100ML",     39.95),
    ("PERFUME AL HARAMAIN AMBER OUD GOLD EDP 120ML",                         34.95),
    # ── AL WATANIAH ──────────────────────────────────────────────────────────
    ("PERFUME AL WATANIAH ABYAT EDP 100ML",              8.70),
    ("PERFUME AL WATANIAH AMEERATI EDP 100ML",           8.55),
    ("PERFUME AL WATANIAH ATTAR AL WESAL EDP 100ML",    11.95),
    ("PERFUME AL WATANIAH BAREEQ AL DHAHAB EDP 100ML",   8.45),
    ("PERFUME AL WATANIAH KENZ AL MALIK EDP 100ML",      9.95),
    ("PERFUME AL WATANIAH OUD MSYTERY INTENSE EDP 100ML",12.55),
    ("PERFUME AL WATANIAH ROSE MYSTERY INTENSE EDP 100ML",12.55),
    ("PERFUME AL WATANIAH SABAH AL WARD EDP 100ML",     10.95),
    ("PERFUME AL WATANIAH SABAH AL WARD SUGAR EDP 100ML",12.45),
    ("PERFUME AL WATANIAH SABAH AL WARD VALENTINE EDP 100ML",25.45),
    ("PERFUME AL WATANIAH SHAGAF AL WARD EDP 100ML",   10.35),
    ("PERFUME AL WATANIAH SPECIAL OUD EDP 100ML",        8.70),
    ("PERFUME AL WATANIAH SULTAN AL LAIL EDP 100ML",   10.50),
    ("PERFUME AL WATANIAH THAHAANI EDP 100ML",           9.95),
    ("PERFUME AL WATANIAH TIARA EDP 100ML",             10.50),
    # ── ANWAR ────────────────────────────────────────────────────────────────
    ("BODY CREAM ANWAR ANGEL 200ML",                   12.50),
    ("BODY CREAM ANWAR ASAD 200ML",                    12.50),
    ("BODY CREAM ANWAR CLUB DE NUIT INTENSE MAN 200ML",12.50),
    ("BODY CREAM ANWAR FAKHAR ROSE 200ML",             12.50),
    ("BODY CREAM ANWAR YARA 200ML",                    12.50),
    ("BODY CREAM ANWAR YARA CANDY 200ML",              12.50),
    # ── ARMAF ────────────────────────────────────────────────────────────────
    ("BODY MIST ARMAF I AM CELESTIAL 250ML",            8.50),
    ("BODY MIST ARMAF I AM DIVINE 250ML",               8.50),
    ("BODY MIST ARMAF I AM EBA 250ML",                  8.50),
    ("BODY MIST ARMAF I AM ELIXIR OF THE WILD 250ML",   8.50),
    ("BODY MIST ARMAF I AM ENIGMA 250ML",               8.50),
    ("BODY MIST ARMAF I AM FIRE 250ML",                 8.50),
    ("BODY MIST ARMAF I AM FROZEN BLOOSOM",             8.50),
    ("BODY MIST ARMAF I AM HEAVENLY 250ML",             8.50),
    ("BODY MIST ARMAF I AM KAYA 250ML",                 8.50),
    ("BODY MIST ARMAF I AM LEGACY 250ML",               8.50),
    ("BODY MIST ARMAF I AM LYNA 250ML",                 8.50),
    ("BODY MIST ARMAF I AM MAGIC 250ML",                8.50),
    ("BODY MIST ARMAF I AM SELFLESS 250ML",             8.50),
    ("BODY MIST ARMAF I AM VELVET MIRAGE 250ML",        8.50),
    ("DESODORANTE ARMAF 200ML ODYSSEY HOMME",           3.50),
    ("DESODORANTE ARMAF 200ML ODYSSEY HOMME WHITE",     3.50),
    ("PERFUME ARMAF BEACH PARTY EDP 100ML",            25.00),
    ("PERFUME ARMAF CHECKMATE KING EDP 100ML",         27.50),
    ("PERFUME ARMAF CHECKMATE QUEEN EDP 100ML",        23.45),
    ("PERFUME ARMAF CLUB DE NUIT BLING EDP 75ML",      35.95),
    ("PERFUME ARMAF CLUB DE NUIT IMPERIALE EDP 105ML", 26.95),
    ("PERFUME ARMAF CLUB DE NUIT INTENSE MAN EDT 105ML",22.95),
    ("PERFUME ARMAF CLUB DE NUIT LIONHEART MAN EDP 100ML",32.95),
    ("PERFUME ARMAF CLUB DE NUIT LIONHEART WOMAN EDP 100ML",25.95),
    ("PERFUME ARMAF CLUB DE NUYT MALEKA EDP 100ML",    26.45),
    ("PERFUME ARMAF CLUB DE NUIT MILESTONE EDP 105ML", 22.70),
    ("PERFUME ARMAF CLUB DE NUIT PRECIEUX I EXTRAIT DE PARFUM 55ML",  34.70),
    ("PERFUME ARMAF CLUB DE NUIT PRECIEUX IV EXTRAIT DE PARFUM 55ML", 43.45),
    ("PERFUME ARMAF CLUB DE NUIT SILLAGE EDP 100ML",   24.95),
    ("PERFUME ARMAF CLUB DE NUIT UNTOLD EDP 105ML",    28.95),
    ("PERFUME ARMAF CLUB DE NUIT URBAN MAN ELIXIR EDP 105ML",23.45),
    ("PERFUME ARMAF CLUB DE NUIT WOMAN EDP 105ML",     20.45),
    ("PERFUME ARMAF CONNOISSEUR MAN EDP 100ML",        21.85),
    ("PERFUME ARMAF CONNOISSEUR WOMAN EDP 100ML",      19.95),
    ("PERFUME ARMAF DELIGHTS ISLAND BLISS EDP 100ML",  25.45),
    ("PERFUME ARMAF DELIGHTS YUM YUM EDP 100ML",       27.95),
    ("PERFUME ARMAF ODYSSEY AOUD EDP 100ML",           16.70),
    ("PERFUME ARMAF ODYSSEY BA HA MAS EDP 100ML",      28.35),
    ("PERFUME ARMAF ODYSSEY BLACK FOREST EDP 100ML",   19.95),
    ("PERFUME ARMAF ODYSSEY CANDEE EDP 100ML",         16.45),
    ("PERFUME ARMAF ODYSSEY DUBAI CHOCOLAT EDP 100ML", 11.95),
    ("PERFUME ARMAF ODYSSEY HOMME EDP 100ML",          16.20),
    ("PERFUME ARMAF ODYSSEY HOMME WHITE INTENSE EDP 100ML",16.95),
    ("PERFUME ARMAF ODYSSEY LIMONI EDP 100ML",         16.70),
    ("PERFUME ARMAF ODYSSEY MANDARIN SKY EDP 100ML",   20.00),
    ("PERFUME ARMAF ODYSSEY MANDARIN SKY ELIXIR EDP 100ML",35.00),
    ("PERFUME ARMAF ODYSSEY MARSHMALLOW EDP 100ML",    26.65),
    ("PERFUME ARMAF ODYSSEY MEGA EDP 100ML",           16.85),
    ("PERFUME ARMAF ODYSSEY REVOLUTION EDP 100ML",     17.70),
    ("PERFUME ARMAF ODYSSEY SPECTRA RAINBOW EDP 100ML",16.35),
    ("PERFUME ARMAF ODYSSEY TOFFEE COFFEE EDP 100ML",  29.65),
    ("PERFUME ARMAF ODYSSEY TYRANT EDP 100ML",         16.70),
    # ── FOLIE PURE ───────────────────────────────────────────────────────────
    ("PERFUME FOLIE PURE 30ML EDP DESIREE",             5.75),
    ("PERFUME FOLIE PURE 30ML EDP DREAM DAYS",          5.75),
    ("PERFUME FOLIE PURE 30ML EDP ELECTRIC LOVE",       5.75),
    ("PERFUME FOLIE PURE 30ML EDP ESENCIA RAGIA",       5.75),
    ("PERFUME FOLIE PURE 30ML EDP ETERNAL FLAME",       5.75),
    ("PERFUME FOLIE PURE 30ML EDP FASHION CLUB",        5.75),
    ("PERFUME FOLIE PURE 30ML EDP GREEN DREAM",         5.75),
    ("PERFUME FOLIE PURE 30ML EDP LUXE ROUGE",          5.75),
    ("PERFUME FOLIE PURE 30ML EDP NEW FLOWER",          5.75),
    ("PERFUME FOLIE PURE 30ML EDP PINK LIFE",           5.75),
    ("PERFUME FOLIE PURE 30ML EDP PURPLE PEARL",        5.75),
    ("PERFUME FOLIE PURE 30ML EDP VIP STREET",          5.75),
    # ── FRENCH AVENUE ────────────────────────────────────────────────────────
    ("PERFUME FRENCH AVENUE VENENO BIANCO EDP 100ML",  32.95),
    ("PERFUME FRENCH AVENUE VENENO SCARLET EDP 100ML", 31.95),
    ("PERFUME FRENCH AVENUE VULCAN BAIE EDP 100ML",    24.70),
    ("PERFUME FRENCH AVENUE VULCAN FEU EDP 100ML",     28.60),
    # ── KARSEELL ─────────────────────────────────────────────────────────────
    ("CONDICIONADOR KARSEELL MACA ESSENCE REPAIR 500ML", 6.45),
    ("MASCARA CAPILAR KARSEELL CAPILAR MACA POWER 500ML",5.00),
    ("OLEO CAPILAR KARSEELL MACA ESSENCE 50ML",          5.75),
    # ── LATTAFA ──────────────────────────────────────────────────────────────
    ("AMBIENTADOR LATTAFA AMEERAT AL ARAB AIR FRESHENER 300ML", 4.25),
    ("AMBIENTADOR LATTAFA KHAMRAH AIR FRESHENER 300ML",          4.25),
    ("BODY SPLASH LATTAFA ANGHAM 250ML",                8.50),
    ("BODY SPLASH LATTAFA BADEE AL OUD NOBLE BLUSH 250ML",8.50),
    ("BODY SPLASH LATTAFA ECLAIRE 250ML",               8.50),
    ("BODY SPLASH LATTAFA FAKHAR WOMEN 250ML",          8.50),
    ("BODY SPLASH LATTAFA HAYA 250ML",                  8.50),
    ("BODY SPLASH LATTAFA MAYAR CHERRY INTENSE 250ML",  8.50),
    ("BODY SPLASH LATTAFA MAYAR NATURAL INTENSE 250ML", 8.50),
    ("BODY SPLASH LATTAFA SEHR 250ML",                  8.50),
    ("BODY SPLASH LATTAFA YARA EDP 250ML",              8.50),
    ("BODY SPLASH LATTAFA YARA TOUS 250ML",             8.50),
    ("DESODORANTE LATTAFA 200ML ANA ABIYEDH",           3.00),
    ("DESODORANTE LATTAFA 200ML ASAD",                  3.00),
    ("DESODORANTE LATTAFA 200ML ASAD BOURBON",          3.00),
    ("DESODORANTE LATTAFA 200ML ASAD ZANZIBAR",         3.00),
    ("DESODORANTE LATTAFA 200ML ASDAAF AMEERAT AL ARAB",3.00),
    ("DESODORANTE LATTAFA 200ML BADEE AL OUD AMETHYST", 3.00),
    ("DESODORANTE LATTAFA 200ML BADEE AL OUD HONOR GLORY",3.00),
    ("DESODORANTE LATTAFA 200ML BADEE AL OUD OUD FOR GLORY",3.00),
    ("DESODORANTE LATTAFA 200ML BADEE AL OUD SUBLIME",  3.00),
    ("DESODORANTE LATTAFA 200ML FAKHAR EXTRAIT",        3.00),
    ("DESODORANTE LATTAFA 200ML FAKHAR MAN",            3.00),
    ("DESODORANTE LATTAFA 200ML FAKHAR WOMEN",          3.00),
    ("DESODORANTE LATTAFA 200ML HAYA",                  3.00),
    ("DESODORANTE LATTAFA 200ML HAYAATI",               3.00),
    ("DESODORANTE LATTAFA 200ML HAYAATI AL MALEKY",     3.00),
    ("DESODORANTE LATTAFA 200ML KHAMRAH QAHWA",         3.00),
    ("DESODORANTE LATTAFA 200ML MAYAR NATURAL INTENSE", 3.00),
    ("DESODORANTE LATTAFA 200ML QAED AL FURSAN",        3.00),
    ("DESODORANTE LATTAFA 200ML YARA",                  3.00),
    ("DESODORANTE LATTAFA 200ML YARA CANDY",            3.00),
    ("DESODORANTE LATTAFA 200ML YARA MOI",              3.00),
    ("DESODORANTE LATTAFA 200ML YARA TOUS",             3.00),
    ("PERFUME LATTAFA 24 CARAT PURE GOLD EDP 100ML",    9.70),
    ("PERFUME LATTAFA 24 CARAT WHITE GOLD EDP 100ML",   9.70),
    ("PERFUME LATTAFA AJWAD EDP 60ML",                 10.40),
    ("PERFUME LATTAFA AJWAD PINK TO PINK EDP 60ML",    10.30),
    ("PERFUME LATTAFA AL NASHAMA CAPRICE EDP 100ML",   14.70),
    ("PERFUME LATTAFA AL NOLE SAFEER EDP 100ML",       14.45),
    ("PERFUME LATTAFA AL NOBLE WAZEER EDP 100ML",      14.45),
    ("PERFUME LATTAFA ANA ABIYEDH ROUGE EDP 60ML",      9.70),
    ("PERFUME LATTAFA ASAD BOURBON EDP 100ML",         18.95),
    ("PERFUME LATTAFA ASAD EDP 100ML",                 15.70),
    ("PERFUME LATTAFA ASAD ELIXIR EDP 100ML",          19.95),
    ("PERFUME LATTAFA ASAD ZANZIBAR LIMITED EDITION EDP 100ML",13.95),
    ("PERFUME LATTAFA ASDAAF AMEER AL ARAB EDP 100ML", 10.20),
    ("PERFUME LATTAFA ASDAAF AMEER AL ARAB IMPERIUM EDP 100ML",10.20),
    ("PERFUME LATTAFA ASDAAF AMEERAT AL ARAB EDP 100ML", 9.95),
    ("PERFUME LATTAFA ASDAAF AMEERAT AL ARAB PRIVE ROSE EDP 100ML",9.95),
    ("PERFUME LATTAFA ASDAAF ANDALEEB EDP 100ML",       9.95),
    ("PERFUME LATTAFA ASDAAF ANDALEEB FLORA EDP 100ML", 9.95),
    ("PERFUME LATTAFA ATHEERI EDP 100ML",              46.45),
    ("PERFUME LATTAFA BADE'E AL OUD AMETHYST EDP 100ML",14.30),
    ("PERFUME LATTAFA BADE'E AL OUD HONOR GLORY EDP 100ML",14.45),
    ("PERFUME LATTAFA BADE'E AL OUD NOBLE BLUSH EDP 100ML",14.45),
    ("PERFUME LATTAFA BADE'E AL OUD OUD FOR GLORY EDP 100ML",14.45),
    ("PERFUME LATTAFA BADE'E AL OUD SUBLIME EDP 100ML",14.45),
    ("PERFUME LATTAFA CONFIDENTIAL PRIVATE PLATINUM EDP 100ML",9.95),
    ("PERFUME LATTAFA ECLAIRE BANOFFI EDP 100ML",      20.95),
    ("PERFUME LATTAFA ECLAIRE EDP 100ML",              15.85),
    ("PERFUME LATTAFA ECLAIRE PISTACHE EDP 100ML",     20.95),
    ("PERFUME LATTAFA EJAAZI EDP 100ML",                9.45),
    ("PERFUME LATTAFA EMEER EDP 100ML",                24.45),
    ("PERFUME LATTAFA FAKHAR EXTRAIT EDP 100ML",       13.85),
    ("PERFUME LATTAFA FAKHAR PLATIN EDP 100ML",        13.95),
    ("PERFUME LATTAFA FAKHAR WOMEN EDP 100ML",         16.45),
    ("PERFUME LATTAFA HABIK EDP 100ML",                14.35),
    ("PERFUME LATTAFA HAYAATI AL MALEKY EDP 100ML",     9.95),
    ("PERFUME LATTAFA HAYAATI FLORENCE EDP 100ML",      9.70),
    ("PERFUME LATTAFA HAYAATI GOLD EDP 100ML",          8.85),
    ("PERFUME LATTAFA HER CONFESSION EDP 100ML",       19.95),
    ("PERFUME LATTAFA HIS CONFESSION EDP 100ML",       19.95),
    ("PERFUME LATTAFA KHAMRAH DUKHAN EDP 100ML",       13.95),
    ("PERFUME LATTAFA KHAMRAH EDP 100ML",              13.95),
    ("PERFUME LATTAFA KHAMRAH QAHWA EDP 100ML",        14.70),
    ("PERFUME LATTAFA KING OF ARABIA EDP 100ML",       24.45),
    ("PERFUME LATTAFA LAIL MALEKI EDP 100ML",           9.65),
    ("PERFUME LATTAFA MAAHIR BLACK EDP 100ML",         13.20),
    ("PERFUME LATTAFA MAAHIR EDP 100ML",               11.95),
    ("PERFUME LATTAFA MAAHIR LEGACY EDP 100ML",        15.95),
    ("PERFUME LATTAFA MAYAR CHERRY INTENSE EDP 100ML", 13.45),
    ("PERFUME LATTAFA MAYAR EDP 100ML",                14.95),
    ("PERFUME LATTAFA MAYAR NATURAL INTENSE EDP 100ML",13.70),
    ("PERFUME LATTAFA MUSAMAM WHITE INTENSE EDP 100ML",24.45),
    ("PERFUME LATTAFA PETRA EDP 100ML",                16.75),
    ("PERFUME LATTAFA PRIDE AL QIAM GOLD EDP 100ML",   16.90),
    ("PERFUME LATTAFA PRIDE AL QIAM SILVER EDP 100ML", 17.45),
    ("PERFUME LATTAFA PRIDE ANSAAM GOLD EDP 100ML",    16.40),
    ("PERFUME LATTAFA PRIDE ANSAAM SILVER EDP 100ML",  16.90),
    ("PERFUME LATTAFA PRIDE ART OF UNIVERSE EDP 100ML",22.70),
    ("PERFUME LATTAFA PRIDE ISHQ AL SHUYUKH GOLD EDP 100ML",15.95),
    ("PERFUME LATTAFA PRIDE LA COLLECTION D'ANTIQUITES 1910 EDP 100ML",20.45),
    ("PERFUME LATTAFA PRIDE NEBRAS EDP 100ML",         18.70),
    ("PERFUME LATTAFA PRIDE NEBRAS ELIXIR EDP 100ML",  27.95),
    ("PERFUME LATTAFA PRIDE SHAHEEN GOLD EDP 100ML",   16.30),
    ("PERFUME LATTAFA PRIDE SHAHEEN SILVER EDP 100ML", 16.30),
    ("PERFUME LATTAFA QAED AL FURSAN EDP 90ML",        10.15),
    ("PERFUME LATTAFA QAED AL FURSAN UNLIMITED EDP 90ML",9.45),
    ("PERFUME LATTAFA QAED AL FURSAN UNTAMED EDP 90ML", 9.45),
    ("PERFUME LATTAFA QIMMAH FOR MEN EDP 100ML",       10.20),
    ("PERFUME LATTAFA QIMMAH FOR WOMEN EDP 100ML",     13.70),
    ("PERFUME LATTAFA SAKEENA EDP 100ML",              13.65),
    ("PERFUME LATTAFA TERIAQ INTENSE EDP 100ML",       17.95),
    ("PERFUME LATTAFA THE KINGDOM MAN EDP 100ML",      17.95),
    ("PERFUME LATTAFA THE KINGDOM WOMAN EDP 100ML",    14.85),
    ("PERFUME LATTAFA VICTORIA EDP 100ML",             16.20),
    ("PERFUME LATTAFA YARA CANDY EDP 100ML",           13.65),
    ("PERFUME LATTAFA YARA EDP 100ML",                 13.95),
    ("PERFUME LATTAFA YARA ELIXIR EDP 100ML",          18.95),
    ("PERFUME LATTAFA YARA MOI EDP 100ML",             13.70),
    ("PERFUME LATTAFA YARA TOUS EDP 100ML",            13.70),
    # ── MAISON ALHAMBRA ──────────────────────────────────────────────────────
    ("PERFUME MAISON ALHAMBRA ALPINE HOMME SPORT EDP 100ML",   12.95),
    ("PERFUME MAISON ALHAMBRA CHANTS TENDERINA EDP 100ML",     10.90),
    ("PERFUME MAISON ALHAMBRA EXQUISITE CLUB POUR HOMME EDP 100ML",9.95),
    ("PERFUME MAISON ALHAMBRA GALACTIC MEN ELIXIR EDP 100ML",   9.95),
    ("PERFUME MAISON ALHAMBRA GALACTIC MEN INTENSE EDP 100ML",  9.85),
    ("PERFUME MAISON ALHAMBRA INFINI INTOXICATING CHERRY EDP 100ML",12.35),
    ("PERFUME MAISON ALHAMBRA INTRUDE EDP 100ML",              12.95),
    ("PERFUME MAISON ALHAMBRA JEAN LOWE IMMORTEL EDP 100ML",   15.75),
    ("PERFUME MAISON ALHAMBRA JORGE DI PROFUMO AQUA EDP 100ML",11.95),
    ("PERFUME MAISON ALHAMBRA JORGE DI PROFUMO DEEP BLUE EDP 100ML",11.95),
    ("PERFUME MAISON ALHAMBRA JORGE DI PROFUMO EDP 100ML",     11.95),
    ("PERFUME MAISON ALHAMBRA LA ROUGE BAROQUE EDP 100ML",     10.75),
    ("PERFUME MAISON ALHAMBRA LA ROUGE BAROQUE EXTREME EDP 100ML",10.95),
    ("PERFUME MAISON ALHAMBRA LA VIVACITE INTENSA EDP 100ML",  11.45),
    ("PERFUME MAISON ALHAMBRA LA VOIE EDP 100ML",              10.85),
    ("PERFUME MAISON ALHAMBRA LUXE BOLD EDP 100ML",            12.45),
    ("PERFUME MAISON ALHAMBRA NO.2 MEN EDP 80ML",              12.95),
    ("PERFUME MAISON ALHAMBRA PHILOS CENTRO EDP 100ML",        10.60),
    ("PERFUME MAISON ALHAMBRA PHILOS OPUS NOIR EDP 100ML",      9.45),
    ("PERFUME MAISON ALHAMBRA PHILOS SHINE EDP 100ML",         10.95),
    ("PERFUME MAISON ALHAMBRA REYNA POUR FEMME EDP 100ML",     10.65),
    ("PERFUME MAISON ALHAMBRA ROSE ORIGAMI EDP 100ML",          9.45),
    ("PERFUME MAISON ALHAMBRA ROSE SEDUCTION VIP POUR FEMME EDP 100ML",16.95),
    ("PERFUME MAISON ALHAMBRA SO CANDID POUR FEMME EDP 100ML", 12.65),
    ("PERFUME MAISON ALHAMBRA VICTORIOSO EDP 100ML",           13.95),
    ("PERFUME MAISON ALHAMBRA VICTORIOSO NERO EDP 100ML",      13.95),
    ("PERFUME MAISON ALHAMBRA YEAH! MAN EDP 100ML",            11.35),
    ("PERFUME MAISON ALHAMBRA YEAH! MAN PARFUM EDP 100ML",     12.70),
    # ── ORIENTICA ────────────────────────────────────────────────────────────
    ("PERFUME ORIENTICA ROYAL AMBER EDP 80ML",         47.85),
    # ── RASASI ───────────────────────────────────────────────────────────────
    ("PERFUME RASASI HAWAS BLACK EDP 100ML",           22.45),
    ("PERFUME RASASI HAWAS DIVA EDP 100ML",            41.95),
    ("PERFUME RASASI HAWAS FOR HIM EDP 100ML",         17.95),
    ("PERFUME RASASI HAWAS ICE EDP 100ML",             30.95),
    ("PERFUME RASASI HAWAS MALIBU EDP 100ML",          33.45),
    ("PERFUME RASASI HAWAS TROPICAL EDP 100ML",        28.95),
    # ── RAYHAAN ──────────────────────────────────────────────────────────────
    ("PERFUME RAYHAAN OCEAN RUSH EDP 100ML",           19.95),
    # ── VICTORIA'S SECRET ────────────────────────────────────────────────────
    ("BODY LOTION VICTORIA'S SECRET AQUA KISS SHIMMER 236ML",       13.25),
    ("BODY LOTION VICTORIA'S SECRET BARE VANILLA SHIMMER 236ML",    13.25),
    ("BODY LOTION VICTORIA'S SECRET COCONUT PASSION SHIMMER 236ML", 13.25),
    ("BODY LOTION VICTORIA'S SECRET PURE SEDUCTION SHIMMER 236ML",  13.25),
    ("BODY LOTION VICTORIA'S SECRET TEMPTATION SHIMMER 236ML",      13.25),
    ("BODY SPLASH VICTORIA'S SECRET AMBER ROMANCE 250ML",           12.50),
    ("BODY SPLASH VICTORIA'S SECRET AQUA KISS 250ML",               12.50),
    ("BODY SPLASH VICTORIA'S SECRET BARE VANILLA 250ML",            12.50),
    ("BODY SPLASH VICTORIA'S SECRET BARE VANILLA SHIMMER 250ML",    13.25),
    ("BODY SPLASH VICTORIA'S SECRET COCONUT PASSION 250ML",         12.50),
    ("BODY SPLASH VICTORIA'S SECRET COCONUT PASSION SHIMMER 250ML", 13.25),
    ("BODY SPLASH VICTORIA'S SECRET LOVE SPELL 250ML",              12.50),
    ("BODY SPLASH VICTORIA'S SECRET LOVE SPELL SHIMMER 250ML",      13.25),
    ("BODY SPLASH VICTORIA'S SECRET PURE SEDUCTION 250ML",          12.50),
    ("BODY SPLASH VICTORIA'S SECRET ROMANTIC 250ML",                12.50),
    ("BODY SPLASH VICTORIA'S SECRET RUSH 250ML",                    12.50),
    ("BODY SPLASH VICTORIA'S SECRET TEMPTATION 250ML",              12.50),
    # ── XERJOFF ──────────────────────────────────────────────────────────────
    ("PERFUME XERJOFF ERBA PURA EDP 100ML",           165.00),
    # ── ZIMAYA ───────────────────────────────────────────────────────────────
    ("PERFUME ZIMAYA FATIMA PINK EXTRAIT DE PARFUM 100ML",14.95),
    ("PERFUME ZIMAYA TIRAMISU CARAMEL EDP 100ML",       21.45),
    ("PERFUME ZIMAYA TIRAMISU COCO EDP 100ML",          20.95),
]

QTY_RE = re.compile(r"\b(\d+(?:\.\d+)?\s*(?:G|ML))\s*$", re.IGNORECASE)


def extract_quantity(descripcion):
    m = QTY_RE.search(descripcion)
    if m:
        qty = m.group(1).upper().replace(" ", "")
        nombre = descripcion[: m.start()].strip()
        return nombre, qty
    return descripcion, None


def to_folder_name(name, max_len=100):
    clean = re.sub(r'[<>:"/\\|?*\x00-\x1f]', "_", name)
    clean = re.sub(r"\s+", "_", clean.strip())
    return clean[:max_len]


def main():
    OUTPUT_DIR.mkdir(exist_ok=True)
    seen = {}
    total = 0

    for descripcion, precio in PRODUCTOS_RAW:
        nombre, cantidad = extract_quantity(descripcion)

        base   = to_folder_name(nombre)
        n      = seen.get(base, 0)
        seen[base] = n + 1
        folder = base if n == 0 else f"{base}_{n}"

        pdir = OUTPUT_DIR / folder
        pdir.mkdir(exist_ok=True)

        info = {
            "nombre":      nombre,
            "cantidad":    cantidad,
            "precio":      precio,
            "descripcion": descripcion,
        }
        (pdir / "info.json").write_text(
            json.dumps(info, ensure_ascii=False, indent=2),
            encoding="utf-8",
        )
        total += 1

    print(f"Creados {total} productos en '{OUTPUT_DIR}/'")


if __name__ == "__main__":
    main()
