const CATALOGO_VAPERS = [

  // ── ELF BAR ICE KING ──────────────────────────────────────────────
  {
    marca: "ELF BAR",
    modelo: "Ice King",
    nombre: "Dragon Strawnana",
    descripcion: "Exótico cóctel de pitaya, fresa y banana. Una mezcla tropical dulce y refrescante que explota en cada calada.",
    imagen: "https://tiendavapor.com/cdn/shop/files/40kelfbarstrawnana2.png?v=1772653992",
    puffs: 40000,
    nicotina: "5%",
    bateria: "850 mAh",
    liquido: "22 ml",
    carga: "USB-C",
    features: ["5 niveles de frío ajustables", "Doble airflow", "Batería 850 mAh"],
    precio: 27500,
    moneda: "ARS"
  },
  {
    marca: "ELF BAR",
    modelo: "Ice King",
    nombre: "Summer Edition Triple Berry",
    descripcion: "Mezcla de tres berries: arándano, frambuesa y mora con un final refrescante que potencia la experiencia.",
    imagen: "https://tiendavapor.com/cdn/shop/files/elfbartripleberry.jpg?v=1773665501",
    puffs: 40000,
    nicotina: "5%",
    bateria: "850 mAh",
    liquido: "22 ml",
    carga: "USB-C",
    features: ["5 niveles de frío ajustables", "Doble airflow", "Batería 850 mAh"],
    precio: 27500,
    moneda: "ARS"
  },
  {
    marca: "ELF BAR",
    modelo: "Ice King",
    nombre: "Sour Lush Gummy",
    descripcion: "Réplica exacta del sabor de tus gomitas ácidas favoritas: combinación perfecta entre acidez y dulzura.",
    imagen: "https://tiendavapor.com/cdn/shop/files/elfbarsputlushgummy40000.png?v=1773251536",
    puffs: 40000,
    nicotina: "5%",
    bateria: "850 mAh",
    liquido: "22 ml",
    carga: "USB-C",
    features: ["5 niveles de frío ajustables", "Doble airflow", "Batería 850 mAh"],
    precio: 27500,
    moneda: "ARS"
  },

  // ── ELF BAR TRIO ──────────────────────────────────────────────────
  {
    marca: "ELF BAR",
    modelo: "Trio",
    nombre: "Blue Razz Ice",
    descripcion: "Frambuesa azul dulce y ácida con toque helado que intensifica cada calada. Tres perfiles personalizables en un solo dispositivo.",
    imagen: "https://tiendavapor.com/cdn/shop/files/ElfbarTrioBlueRazz.png?v=1772653690",
    puffs: 40000,
    nicotina: "5%",
    bateria: "Recargable",
    liquido: "—",
    carga: "USB-C",
    features: ["3 perfiles ajustables (acidez · hielo · dulce)", "Modo Turbo", "4 resistencias mesh"],
    precio: 27500,
    moneda: "ARS"
  },
  {
    marca: "ELF BAR",
    modelo: "Trio",
    nombre: "Watermelon Ice",
    descripcion: "Dulzura jugosa de sandía combinada con frescor helado. Ligero y refrescante, perfecto para el verano.",
    imagen: "https://tiendavapor.com/cdn/shop/files/WatermelonICe_d6d6f93e-c258-4e3a-84e0-c0b6a50a8814.jpg?v=1755806566",
    puffs: 40000,
    nicotina: "5%",
    bateria: "Recargable",
    liquido: "—",
    carga: "USB-C",
    features: ["3 perfiles ajustables (acidez · hielo · dulce)", "Modo Turbo", "4 resistencias mesh"],
    precio: 27500,
    moneda: "ARS"
  },
  {
    marca: "ELF BAR",
    modelo: "Trio",
    nombre: "Cool Menthol",
    descripcion: "Frescor mentolado puro e intenso. Un acabado frío y limpio que se mantiene desde la primera hasta la última calada.",
    imagen: "https://tiendavapor.com/cdn/shop/files/CoolMenthol.png?v=1755787566",
    puffs: 40000,
    nicotina: "5%",
    bateria: "Recargable",
    liquido: "—",
    carga: "USB-C",
    features: ["3 perfiles ajustables (acidez · hielo · dulce)", "Modo Turbo", "4 resistencias mesh"],
    precio: 27500,
    moneda: "ARS"
  },
  {
    marca: "ELF BAR",
    modelo: "Trio",
    nombre: "Pomegranate Blast",
    descripcion: "Granada intensa y jugosa con toque refrescante al exhalar. Frutal profundo, ligeramente ácido y equilibrado.",
    imagen: "https://tiendavapor.com/cdn/shop/files/PineappleLime_d19c9d45-8a53-4139-8e9e-d0c19ab09764.png?v=1772653690",
    puffs: 40000,
    nicotina: "5%",
    bateria: "Recargable",
    liquido: "—",
    carga: "USB-C",
    features: ["3 perfiles ajustables (acidez · hielo · dulce)", "Modo Turbo", "4 resistencias mesh"],
    precio: 27500,
    moneda: "ARS"
  },

  // ── IGNITE V400 ───────────────────────────────────────────────────
  {
    marca: "IGNITE",
    modelo: "V400",
    nombre: "Mix Banana Ice / Strawberry Ice",
    descripcion: "Banana cremosa con toque helado + fresa jugosa con frescura mentolada. Dos sabores únicos en un solo dispositivo.",
    imagen: "https://tiendavapor.com/cdn/shop/files/v400mixBananaicestrawberryice_1120x.png?v=1772837227",
    puffs: 40000,
    nicotina: "5%",
    bateria: "Recargable",
    liquido: "—",
    carga: "USB-C",
    features: ["Dual Tank (2 sabores)", "Pantalla digital", "Doble mesh"],
    precio: 28500,
    moneda: "ARS"
  },
  {
    marca: "IGNITE",
    modelo: "V400",
    nombre: "Mix Grape Ice / Watermelon Ice",
    descripcion: "Uva dulce e intensa con hielo + sandía fresca y jugosa ice. Dual flavor vibrante y ultra refrescante.",
    imagen: "https://tiendavapor.com/cdn/shop/files/v400mixgrapeicewatermelonice.png?v=1757989391",
    puffs: 40000,
    nicotina: "5%",
    bateria: "Recargable",
    liquido: "—",
    carga: "USB-C",
    features: ["Dual Tank (2 sabores)", "Pantalla digital", "Doble mesh"],
    precio: 28500,
    moneda: "ARS"
  },
  {
    marca: "IGNITE",
    modelo: "V400",
    nombre: "Mix Watermelon Ice / Cherry Ice",
    descripcion: "Sandía refrescante y helada + cereza fría y jugosa. Una combinación frutal vibrante y equilibrada.",
    imagen: "https://tiendavapor.com/cdn/shop/files/v400mixwatermelonicecherryice.png?v=1757989150",
    puffs: 40000,
    nicotina: "5%",
    bateria: "Recargable",
    liquido: "—",
    carga: "USB-C",
    features: ["Dual Tank (2 sabores)", "Pantalla digital", "Doble mesh"],
    precio: 28500,
    moneda: "ARS"
  },
  {
    marca: "IGNITE",
    modelo: "V400",
    nombre: "Mix Grape Ice / Strawberry",
    descripcion: "Uva helada intensa combinada con fresa dulce y natural. Un mix perfecto entre frío y frutado.",
    imagen: "https://tiendavapor.com/cdn/shop/files/v400mixgrapeicestraberry_1120x.png?v=1772653690",
    puffs: 40000,
    nicotina: "5%",
    bateria: "Recargable",
    liquido: "—",
    carga: "USB-C",
    features: ["Dual Tank (2 sabores)", "Pantalla digital", "Doble mesh"],
    precio: 28500,
    moneda: "ARS"
  },
  {
    marca: "IGNITE",
    modelo: "V400",
    nombre: "Mix Grape Pop / Peach Ice",
    descripcion: "Uva explosiva tipo soda + durazno helado y suave. Dulce, efervescente y refrescante al mismo tiempo.",
    imagen: "https://tiendavapor.com/cdn/shop/files/v400mixgrapepoppeachice.png?v=1772653690",
    puffs: 40000,
    nicotina: "5%",
    bateria: "Recargable",
    liquido: "—",
    carga: "USB-C",
    features: ["Dual Tank (2 sabores)", "Pantalla digital", "Doble mesh"],
    precio: 28500,
    moneda: "ARS"
  },
  {
    marca: "IGNITE",
    modelo: "V400",
    nombre: "Ice Mint",
    descripcion: "Menta pura y helada en su máxima expresión. Frescor intenso, limpio y directo en cada calada.",
    imagen: "https://tiendavapor.com/cdn/shop/files/v400MInt_34d91926-fa05-4322-bbf3-e76d3684d2b0.jpg?v=1755783717",
    puffs: 40000,
    nicotina: "5%",
    bateria: "Recargable",
    liquido: "—",
    carga: "USB-C",
    features: ["Pantalla digital", "Doble mesh", "Activación automática"],
    precio: 28500,
    moneda: "ARS"
  },
  {
    marca: "IGNITE",
    modelo: "V400",
    nombre: "Ice Menthol",
    descripcion: "Mentol clásico con intensidad helada. Refrescante y directo, ideal para quienes aman el frío puro.",
    imagen: "https://tiendavapor.com/cdn/shop/files/v400Menthol_e392d7e6-ad88-4dc5-a816-7c2e1fa81701.jpg?v=1772837945",
    puffs: 40000,
    nicotina: "5%",
    bateria: "Recargable",
    liquido: "—",
    carga: "USB-C",
    features: ["Pantalla digital", "Doble mesh", "Activación automática"],
    precio: 28500,
    moneda: "ARS"
  },
  {
    marca: "IGNITE",
    modelo: "V400",
    nombre: "Ice Pineapple",
    descripcion: "Piña tropical fresca con capa de hielo que potencia su dulzura natural. Vibrante y veraniega.",
    imagen: "https://tiendavapor.com/cdn/shop/files/V400_ICe_Pineaplle.png?v=1773748882",
    puffs: 40000,
    nicotina: "5%",
    bateria: "Recargable",
    liquido: "—",
    carga: "USB-C",
    features: ["Pantalla digital", "Doble mesh", "Activación automática"],
    precio: 28500,
    moneda: "ARS"
  },
  {
    marca: "IGNITE",
    modelo: "V400",
    nombre: "Ice Peach Mango Watermelon",
    descripcion: "Triple combinación frutal: durazno suave, mango tropical y sandía fresca. Todo en versión helada.",
    imagen: "https://tiendavapor.com/cdn/shop/files/v400ignitepeachmangoice_1120x.png?v=1757982148",
    puffs: 40000,
    nicotina: "5%",
    bateria: "Recargable",
    liquido: "—",
    carga: "USB-C",
    features: ["Pantalla digital", "Doble mesh", "Activación automática"],
    precio: 28500,
    moneda: "ARS"
  },
  {
    marca: "IGNITE",
    modelo: "V400",
    nombre: "Ice Tutti Fruit Mix",
    descripcion: "Explosión de múltiples frutas heladas en cada calada. Dulce, festivo y ultra refrescante.",
    imagen: "https://tiendavapor.com/cdn/shop/files/Tutti_Fruit_Mix_Ice.webp?v=1773748699",
    puffs: 40000,
    nicotina: "5%",
    bateria: "Recargable",
    liquido: "—",
    carga: "USB-C",
    features: ["Pantalla digital", "Doble mesh", "Activación automática"],
    precio: 28500,
    moneda: "ARS"
  },
  {
    marca: "IGNITE",
    modelo: "V400",
    nombre: "Ice Grape Mix",
    descripcion: "Mezcla intensa de distintas variedades de uva con una capa fría y refrescante. Profundo y persistente.",
    imagen: "https://tiendavapor.com/cdn/shop/files/Grape_Mix_Ignite_V400.png?v=1773748881",
    puffs: 40000,
    nicotina: "5%",
    bateria: "Recargable",
    liquido: "—",
    carga: "USB-C",
    features: ["Pantalla digital", "Doble mesh", "Activación automática"],
    precio: 28500,
    moneda: "ARS"
  }

];
